name: jeuEducatif
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  flutter_dotenv: ^5.1.0
  universal_io: ^2.2.2
  pdf_text: ^0.5.0
  form_field_validator: ^1.1.0
  get_storage: ^2.1.1
  get: ^4.6.6
  shared_preferences: ^2.2.3
  jwt_decoder: ^2.0.1
  file_picker: ^10.2.1
  google_fonts: ^4.0.4
  lottie: ^3.0.0
  uuid: ^3.0.7
  url_launcher: ^6.2.5
  syncfusion_flutter_pdf: ^25.2.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
          - assets/coin.json
          - assets/wave.json
          - assets/images/background.jpeg
          - assets/images/logo.png

